In [109]:
import numpy as np
A = np.random.randint(17, size=(3,3))
print(A,len(A[0].shape))
len(A[0])
len(A)

[[16  2  6]
 [13 12  1]
 [ 3 15 16]] 1


3

In [110]:
def gram_schmidt_columns(A):
    Q, R = np.linalg.qr(A)
    return Q
gram_schmidt_columns(A)

array([[-0.76802458,  0.41853247,  0.48473582],
       [-0.62401997, -0.31887492, -0.7133848 ],
       [-0.14400461, -0.85038189,  0.50607639]])

In [111]:
def mu(b_i, b_j):
    if np.dot(b_i,b_j)!= 0:
        return np.abs((np.dot(b_i,b_j)) / (np.dot(b_j,b_j)))
    else: return 0

In [112]:
def gs(A):
    U = np.zeros((len(A),len(A[0])),dtype=float)
    U[0] = (1.0/(np.abs(np.dot(A[0],A[0]))))*A[0]
    for i in range(1,len(A)):
        j = 0
        while j<i:
            U[i] = U[i] + mu(A[i],U[j])*U[j]
            j = j + 1
        U[i] = A[i] - U[i]
        U[i] = (1.0/np.linalg.norm(U[i]))*U[i]

    return U

In [113]:
U = gs(A)
print(U)

[[ 0.05405405  0.00675676  0.02027027]
 [ 0.01220284  0.93839819 -0.3453403 ]
 [-0.36740472  0.32541561  0.87127404]]


In [114]:
np.zeros((5,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [115]:
np.dot(U[2],U[0])

3.469446951953614e-18

In [101]:
C = np.array([[1,1,0],[2,1,4],[0,10,9]])
C

array([[ 1,  1,  0],
       [ 2,  1,  4],
       [ 0, 10,  9]])

In [102]:
V = gs(C)
V

array([[ 0.5       ,  0.5       ,  0.        ],
       [ 0.12309149, -0.12309149,  0.98473193],
       [-0.69631062,  0.69631062,  0.17407766]])

In [105]:
print(np.dot(V[0],V[1]))

0.0


In [44]:
B=(1.0/np.linalg.norm(A[0]))*A[0]
B

array([0.39477102, 0.8553372 , 0.06579517, 0.32897585])

In [45]:
range(1,len(A)-1)

range(1, 4)

In [50]:
print(range(1,len(A)-1))

range(1, 4)
